<a href="https://colab.research.google.com/github/cagin24/numpy-exercises-solutions/blob/main/solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 101 Numpy Exercises Solutions

In [3]:
#1
import numpy as np
print(np.__version__)

1.21.6


In [8]:
#2
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#3
arr2 = np.ones((3,3),dtype=bool)
arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
#3- Alt
arr3 = np.full((3,3),True,dtype=bool)
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
#4
arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr4[arr4 %2 != 0]

array([1, 3, 5, 7, 9])

In [25]:
#5
arr5 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr5[arr5 % 2 != 0] = -1
arr5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [28]:
#6
arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = arr6.copy()
out[out % 2 != 0] = -1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#6 - alternative
arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr6 % 2 != 0, -1, arr6)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
#7
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
#7 - alternative
arr7 = np.arange(10).reshape(2,-1)
arr7
# -1 : automatically decides which value should be there. eg. 2 * X = 10, X = 5


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a,b),axis = 0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
#8 - alternative
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
#9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a,b),axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [65]:
#9 - alternative
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [80]:
#10 
a = np.array([1,2,3])
arr10 = np.repeat(a,3)
arr10 = np.concatenate((arr10,a,a,a), axis = 0) 
arr10


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [150]:
#10 - alternative
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [151]:
#11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [154]:
#12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [167]:
#13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [186]:
#14
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [221]:
#15
def pair_max(x, y):
    arr = np.array([])
    """Get the maximum of array items"""
    for i in range(len(x)):
      
      if x[i] > y[i]:
        arr = np.append(arr, x[i])
      else:
        arr = np.append(arr, y[i])
    return arr

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [222]:
#15 - alternative
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [229]:
#16 
arr = np.arange(9).reshape(3,3)

arr[:, [1, 0]] = arr[:, [0, 1]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [230]:
#16 - alternative
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]
'''
the first : stands for 1st dimension, second stands for 2nd dimension and so on.
'''


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [231]:
#17 
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [234]:
#17 - alternative
arr = np.arange(9).reshape(3,3)
arr[[0,1],:] = arr[[1,0],:]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [236]:
#18 
arr = np.arange(9).reshape(3,3)
arr[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [239]:
#18 - alternative
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [240]:
#19 
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [244]:
#20
rand_arr20 = np.random.randint(low=5, high=11, size=(5,3)) + np.random.random((5,3))
rand_arr20

array([[ 7.83888843, 10.29223755,  5.75267793],
       [ 7.98194178,  9.36469045,  6.82853099],
       [10.23450102,  9.03889969,  7.00168733],
       [10.51343323,  5.08704942,  6.81639446],
       [ 7.41067178, 10.25178753,  8.75013329]])