<a href="https://colab.research.google.com/github/cagin24/numpy-exercises-solutions/blob/main/solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 101 Numpy Exercises Solutions

In [3]:
#1
import numpy as np
print(np.__version__)

1.21.6


In [8]:
#2
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#3
arr2 = np.ones((3,3),dtype=bool)
arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
#3- Alt
arr3 = np.full((3,3),True,dtype=bool)
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
#4
arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr4[arr4 %2 != 0]

array([1, 3, 5, 7, 9])

In [25]:
#5
arr5 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr5[arr5 % 2 != 0] = -1
arr5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [28]:
#6
arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = arr6.copy()
out[out % 2 != 0] = -1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#6 - alternative
arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr6 % 2 != 0, -1, arr6)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
#7
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
#7 - alternative
arr7 = np.arange(10).reshape(2,-1)
arr7
# -1 : automatically decides which value should be there. eg. 2 * X = 10, X = 5


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a,b),axis = 0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
#8 - alternative
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
#9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a,b),axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [65]:
#9 - alternative
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [80]:
#10 
a = np.array([1,2,3])
arr10 = np.repeat(a,3)
arr10 = np.concatenate((arr10,a,a,a), axis = 0) 
arr10


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [150]:
#10 - alternative
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [151]:
#11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [154]:
#12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [167]:
#13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [186]:
#14
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [221]:
#15
def pair_max(x, y):
    arr = np.array([])
    """Get the maximum of array items"""
    for i in range(len(x)):
      
      if x[i] > y[i]:
        arr = np.append(arr, x[i])
      else:
        arr = np.append(arr, y[i])
    return arr

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [222]:
#15 - alternative
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [229]:
#16 
arr = np.arange(9).reshape(3,3)

arr[:, [1, 0]] = arr[:, [0, 1]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [230]:
#16 - alternative
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]
'''
the first : stands for 1st dimension, second stands for 2nd dimension and so on.
'''


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [231]:
#17 
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [234]:
#17 - alternative
arr = np.arange(9).reshape(3,3)
arr[[0,1],:] = arr[[1,0],:]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [236]:
#18 
arr = np.arange(9).reshape(3,3)
arr[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [239]:
#18 - alternative
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [246]:
#19 
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [244]:
#20
rand_arr20 = np.random.randint(low=5, high=11, size=(5,3)) + np.random.random((5,3))
rand_arr20

array([[ 7.83888843, 10.29223755,  5.75267793],
       [ 7.98194178,  9.36469045,  6.82853099],
       [10.23450102,  9.03889969,  7.00168733],
       [10.51343323,  5.08704942,  6.81639446],
       [ 7.41067178, 10.25178753,  8.75013329]])

In [254]:
#21 
rand_arr = np.random.random([5,3])
np.set_printoptions(precision=3)
rand_arr


array([[0.275, 0.512, 0.005],
       [0.171, 0.035, 0.535],
       [0.977, 0.038, 0.578],
       [0.271, 0.698, 0.14 ],
       [0.382, 0.213, 0.965]])

In [268]:
#22
np.random.seed(100)
rand_arr22 = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=7)
rand_arr22

array([[0.0005434, 0.0002784, 0.0004245],
       [0.0008448, 0.0000047, 0.0001216],
       [0.0006707, 0.0008259, 0.0001367]])

In [270]:
#23
arr23 = np.arange(15)
np.set_printoptions(threshold=6)
arr23

array([ 0,  1,  2, ..., 12, 13, 14])

In [280]:
#24
import sys
arr24 = np.arange(15)
np.set_printoptions(threshold=sys.maxsize)
arr24

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [319]:
#25
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:5]


array([[b'"sepal.length"', b'"sepal.width"', b'"petal.length"',
        b'"petal.width"', b'"variety"'],
       [b'5.1', b'3.5', b'1.4', b'.2', b'"Setosa"'],
       [b'4.9', b'3', b'1.4', b'.2', b'"Setosa"'],
       [b'4.7', b'3.2', b'1.3', b'.2', b'"Setosa"'],
       [b'4.6', b'3.1', b'1.5', b'.2', b'"Setosa"']], dtype=object)

In [329]:
#26
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
iris = np.genfromtxt(url, delimiter=',', dtype=None)

species = np.array([row[4] for row in iris])
species[:10]



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array([b'"variety"', b'"Setosa"', b'"Setosa"', b'"Setosa"', b'"Setosa"',
       b'"Setosa"', b'"Setosa"', b'"Setosa"', b'"Setosa"', b'"Setosa"'],
      dtype='|S12')

In [336]:
#27
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
iris = np.genfromtxt(url, delimiter=',')
iris = iris[1:]
iris2D = np.array([row.tolist()[:4] for row in iris])
iris2D[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [348]:
#28
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
iris = np.genfromtxt(url, delimiter=',')

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = sepallength[1:]

mean, median, standard_deviation = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print('mean:{}, median:{}, std deviation:{}'.format(mean, median, standard_deviation))

mean:5.843333333333334, median:5.8, std deviation:0.8253012917851409


In [353]:
#29
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
iris = np.genfromtxt(url, delimiter=',')

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = sepallength[1:]

s_max, s_min = sepallength.max(), sepallength.min()

sepallength = (sepallength - s_min) / (s_max - s_min)
sepallength

array([0.2222222, 0.1666667, 0.1111111, 0.0833333, 0.1944444, 0.3055556,
       0.0833333, 0.1944444, 0.0277778, 0.1666667, 0.3055556, 0.1388889,
       0.1388889, 0.       , 0.4166667, 0.3888889, 0.3055556, 0.2222222,
       0.3888889, 0.2222222, 0.3055556, 0.2222222, 0.0833333, 0.2222222,
       0.1388889, 0.1944444, 0.1944444, 0.25     , 0.25     , 0.1111111,
       0.1388889, 0.3055556, 0.25     , 0.3333333, 0.1666667, 0.1944444,
       0.3333333, 0.1666667, 0.0277778, 0.2222222, 0.1944444, 0.0555556,
       0.0277778, 0.1944444, 0.2222222, 0.1388889, 0.2222222, 0.0833333,
       0.2777778, 0.1944444, 0.75     , 0.5833333, 0.7222222, 0.3333333,
       0.6111111, 0.3888889, 0.5555556, 0.1666667, 0.6388889, 0.25     ,
       0.1944444, 0.4444444, 0.4722222, 0.5      , 0.3611111, 0.6666667,
       0.3611111, 0.4166667, 0.5277778, 0.3611111, 0.4444444, 0.5      ,
       0.5555556, 0.5      , 0.5833333, 0.6388889, 0.6944444, 0.6666667,
       0.4722222, 0.3888889, 0.3333333, 0.3333333, 

In [354]:
#30 
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
iris = np.genfromtxt(url, delimiter=',')

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = sepallength[1:]

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0) 

softmax(sepallength)

array([0.0022196, 0.0018172, 0.0014878, 0.0013462, 0.0020084, 0.0029961,
       0.0013462, 0.0020084, 0.0011022, 0.0018172, 0.0029961, 0.0016443,
       0.0016443, 0.0009973, 0.0044697, 0.0040443, 0.0029961, 0.0022196,
       0.0040443, 0.0022196, 0.0029961, 0.0022196, 0.0013462, 0.0022196,
       0.0016443, 0.0020084, 0.0020084, 0.002453 , 0.002453 , 0.0014878,
       0.0016443, 0.0029961, 0.002453 , 0.0033112, 0.0018172, 0.0020084,
       0.0033112, 0.0018172, 0.0011022, 0.0022196, 0.0020084, 0.0012181,
       0.0011022, 0.0020084, 0.0022196, 0.0016443, 0.0022196, 0.0013462,
       0.002711 , 0.0020084, 0.0148399, 0.0081443, 0.0134277, 0.0033112,
       0.0090009, 0.0040443, 0.0073693, 0.0018172, 0.0099475, 0.002453 ,
       0.0020084, 0.0049398, 0.0054593, 0.0060335, 0.0036595, 0.0109937,
       0.0036595, 0.0044697, 0.006668 , 0.0036595, 0.0049398, 0.0060335,
       0.0073693, 0.0060335, 0.0081443, 0.0099475, 0.0121499, 0.0109937,
       0.0054593, 0.0040443, 0.0033112, 0.0033112, 

In [355]:
#31 
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
iris = np.genfromtxt(url, delimiter=',')

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = sepallength[1:]

np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])